# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: My little space
description: "My little space for all kind of music, thought, code, TIL, game, misc.."
url: "http://tienna.tk"
author: Nguyen Anh Tien
github: https://github.com/vigov5.github.io
about: I'm a monkey coder who trying to be more creative.
disqus_shortname: ""
google_analytics: UA-66977265-6
avatar_url: /static/img/avatar.png

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/
  book_reviews:
    output: true
    output_ext: .html
    permalink: /book-notes/:path/

social:
    - icon: fa-facebook
      link: "https://facebook.com/vigov5"
    - icon: fa-twitter
      link: "https://twitter.com/vigov5"
    - icon: fa-linkedin
      link: "https://vn.linkedin.com/in/nguyen-anh-tien-751070132"
    - icon: fa-github
      link: "https://github.com/vigov5"

share:
  twitter_username: vigov5

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: Book Notes
      url: /book-notes/
    - text: XML Feed
      url: /feed.xml

baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
